### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by dianzzd** [mopsicus/unity-ios-background-run#1]
Hello, I used your code to run background Xcode, but the rest of the code in Unity was suspended in the background. Do you know how to fix that? Please help us. We would like to pay it if you could help. Thank you
For more convenience, you can contact us on Skype：+8613764700019 Yuan Li

**Comment by mopsicus** [comment]
Hi, you should understand, that not all Unity code will run in background. It doesn't works with Unity Monobehaivour, so, if your code executes in Update() or smth else it will not run in iOS background.
But, if run some function in another thread, like Socket callback it will works.

**Comment by dianzzd** [comment]
Thank you very much!!
